name: Lighthouse CI

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse CI
<<<<<<< HEAD
        uses: treosh/lighthouse-ci-action@v11
=======
        uses: treosh/lighthouse-ci-action@v12
>>>>>>> f2d6c55 (feat: add Lighthouse CI configuration and workflow for performance monitoring)
        with:
          configPath: .lighthouserc.js
          uploadArtifacts: true
          temporaryPublicStorage: true
